### ISSUE TITLE
mt-1生成的css样式为啥是8rpx，不是1嘛？

### ISSUE THREAD

**Issue by xiongchencheng** [MellowCo/unocss-wechat#10]
![image](https://github.com/MellowCo/unocss-wechat/assets/67447838/3f20b859-9732-4b0b-8302-5a90bbef098d)

**Comment by xiongchencheng** [comment]
请问这里自定义规则怎么配置呢？我这里配置了mt-的规则，但是一直没生效

**Comment by xiongchencheng** [comment]
请问这里自定义规则怎么配置呢？我这里配置了mt-的规则，但是一直没生效
export default defineConfig({
  rules: [
    [/^mt-(\d)$/, ([, d]) => ({ margin: `${d}rpx` })]
  ],
  content:{
    pipeline:{
      include
    }
  },
  presets: [
    presetWeapp({
      whRpx:true
    }),
  ],
  separators:'__'
})

**Comment by MellowCo** [comment]
没问题哎

![image](https://github.com/MellowCo/unocss-wechat/assets/47939250/1f7b8722-d53c-4242-99ff-9f800b33721c)
![image](https://github.com/MellowCo/unocss-wechat/assets/47939250/dc2ad412-0a3f-4a0e-b1af-0308c5a70e84)
