### ISSUE TITLE
你好，uniapp里使用插件在vite.config.js开启presetUno后，小程序编译后会提示unexpected token "*"

### ISSUE THREAD

**Issue by jetlong** [MellowCo/unocss-wechat#4]
使用环境：
uniapp vue3

使用过程：
1、在vite.config.js开启presetUno后，如：
` Unocss({ // 使用Unocss
      presets: [
			presetAttributify(),
			presetIcons(),
			presetUno(),
		], 
    }),`

2、在编译为小程序后，会提示 [ WXSS 文件编译错误] ./app.wxss unexpected token "*"

3、在 unocss.config.js 里设置 transformRules ，

`

import presetWeapp from 'unocss-preset-weapp'
import { defineConfig } from 'unocss'
import { transformerAttributify, transformerClass } from 'unocss-preset-weapp/transformer'

const transformRules = {
  '/': '-s111-',
  '*': '-x222-',
  '\\': '-y2221-',
  '\/': '-y2222-',
}

// const transformRules = {}

export default defineConfig({
  presets: [
    // https://github.com/MellowCo/unocss-preset-weapp
    presetWeapp({
		transformRules
	}),
  ],
  shortcuts: [
    {
      'border-base': 'border border-gray-500_10',
      'center': 'flex justify-center items-center',
    },
  ],

  // v0.1.14 unplugin-attributify-to-class 和 unplugin-transform-class 内置到 transformer 中
  transformers: [
    // options 见 https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerAttributify
    transformerAttributify({
		transformRules
	}),

    // options 见 https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerClass
    transformerClass({
		transformRules
	}),
  ]
})

`

错误变为了：

`
[ WXSS 文件编译错误] ./app.wxss   unexpected "\" at pos 6382
`
这个错误，暂无法解决（除非注释掉  presetUno(), ）

**Comment by MellowCo** [comment]
因为 presetUno 不支持在小程序中使用，unocss-preset-weapp 已经包含了 presetUno  一些预设，可以直接使用 unocss-preset-weapp

**Comment by MellowCo** [comment]
[ WXSS 文件编译错误] ./app.wxss unexpected "\" at pos 6382 就是因为这个错误，所以才会有 unocss-preset-weapp 去兼容小程序

**Comment by MellowCo** [comment]
transformRules 没有特殊需求，使用默认的就行了

**Comment by MellowCo** [comment]
配置参考 https://github.com/MellowCo/unocss-preset-weapp/tree/main/examples/uniapp_vue3

**Comment by MellowCo** [comment]
这里说明了小程序不支持原子化css的原因 https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerClass

**Comment by jetlong** [comment]
好的，明白了，非常感谢

**Comment by MellowCo** [comment]
你是在哪看到 unocss-preset-weapp 的 ，怎么会在这个项目反映issues

**Comment by jetlong** [comment]
整个流程是这样的：
1、首先想找的是 uniapp + taiwindcss，结果发现了uniapp + unocss 感觉更方便
2、搜索 uniapp + unocss，在知乎里看到了这个扩展
3、有问题不解，就找到了这个仓库反馈了
