### ISSUE TITLE
能把能把组件加入一下，现在组件没被纳入，只有pages下的文件可以

### ISSUE THREAD

**Issue by qw789** [MellowCo/unocss-wechat#5]

**Comment by MellowCo** [comment]
可以参考这个 https://github.com/unocss/unocss/tree/main/packages/cli#usage

![屏幕截图 2022-12-26 215424](https://user-images.githubusercontent.com/47939250/209556026-8c872c0d-24de-4b60-9699-c3993d701af6.png)
