### ISSUE TITLE
less编译之后没生效

### ISSUE THREAD

**Issue by Sfhh25** [MellowCo/unocss-wechat#6]
<img width="765" alt="image" src="https://github.com/MellowCo/unocss-wechat/assets/93172270/8784f245-996a-4550-99d9-1ef292f83de6">
配置文件是这个,使用的less编译之后好像没有生效

**Comment by Sfhh25** [comment]
> <img alt="图像" width="765" src="https://user-images.githubusercontent.com/93172270/246718820-8784f245-996a-4550-99d9-1ef292f83de6.png"> 配置文件是这个，使用的少编译之后好象没有生命力

<img width="798" alt="image" src="https://github.com/MellowCo/unocss-wechat/assets/93172270/9cbe106a-8b25-40cb-a44e-22b08c6f68c5">
ci改成了这个

**Comment by MellowCo** [comment]
直接导入生成wxss 不就行了，小程序本身不支持less吧

![image](https://github.com/MellowCo/unocss-wechat/assets/47939250/592a67f5-7350-4fb2-9f44-5ea304a281fb)

**Comment by Sfhh25** [comment]
"useCompilerPlugins": ["less"]   加一个这个就支持了,现在我用你的demo跑是可以的,我的项目是跑不动

**Comment by Sfhh25** [comment]
还有一个他会把冒号转成这个,有没有解决方案呢
<img width="258" alt="image" src="https://github.com/MellowCo/unocss-wechat/assets/93172270/1cd6f28c-a19f-4d2f-b68f-6f4364707fd4">

**Comment by MellowCo** [comment]
小程序还是不推荐使用 transformer，把这个去掉

![image](https://github.com/MellowCo/unocss-wechat/assets/47939250/bccea539-402a-4072-839c-06529a168f64)

**Comment by Sfhh25** [comment]
可以了
