### ISSUE TITLE
请问您的.wxml，.wxss文件显示微信的图标是怎么设置的

### ISSUE THREAD

**Issue by hdliyu** [MellowCo/unocss-wechat#8]
大佬请问您的.wxml，.wxss文件显示微信的图标是怎么设置的

**Comment by MellowCo** [comment]
你是指vscode插件吗，搜索 WXML - Language Service 就行了吧

**Comment by hdliyu** [comment]
是的，可是我安装后还是没有您文档中绿色的微信图标 ，另外请问开发微信小程序还要安装别的插件吗
![image](https://github.com/MellowCo/unocss-wechat/assets/13653157/588a9320-0c83-43e0-893f-e9559bf234b6)
