### ISSUE TITLE
微信添加前缀了，导致无法匹配到 unocss 生成类

### ISSUE THREAD

**Issue by szmxx** [MellowCo/unocss-wechat#9]
<img width="1250" alt="image" src="https://github.com/MellowCo/unocss-wechat/assets/24505926/8669a234-e4c0-4a77-aee9-0e376ecc67af">

<img width="1512" alt="image" src="https://github.com/MellowCo/unocss-wechat/assets/24505926/76823b0b-208f-4ff6-8df2-94f2dc0dad83">

**Comment by MellowCo** [comment]
unocss配置加个`prefix`, https://unocss.dev/presets/mini#prefix

生成出来的css文件，就会自动加上前缀了

**Comment by szmxx** [comment]
在自定义组件中，它会根据文件位置，添加不同的前缀类名，其他的就不会。

**miniprogram/components/snackshop**

<img width="598" alt="image" src="https://github.com/MellowCo/unocss-wechat/assets/24505926/fdb3cd61-7184-4bb0-ac72-dc499ab05194">

**miniprogram/components/navigation**

<img width="598" alt="image" src="https://github.com/MellowCo/unocss-wechat/assets/24505926/27ce16d3-45c1-42d3-8075-7c9a96830875">

**miniprogram/pages/home**

<img width="598" alt="image" src="https://github.com/MellowCo/unocss-wechat/assets/24505926/72889e42-ae34-458a-ba27-63e3141b0553">

**Comment by MellowCo** [comment]
那这个微信的机制问题，应该不是unocss问题哦

**Comment by MellowCo** [comment]
我觉得这个只能参考微信自定义组件的样式配置，看看有没有解决方案

https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html

![image](https://github.com/MellowCo/unocss-wechat/assets/47939250/982e57c4-13bf-4df0-9916-f6d8579f824e)
